elasticSearch:
    datastoreImpl: hibernateDatastore
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jasypt:
    algorithm: PBEWITHSHA256AND256BITAES-CBC-BC
    providerName: BC
    password: Bkf227dkAet9HVztUhKS55f3SbBrey
    keyObtentionIterations: 1000


environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://pashionweb.c7nidmmcu7kv.us-east-1.rds.amazonaws.com:3306/pashionweb
            username: pashionweb
            password: ETWxa634WwxGaW6v
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 3
                minIdle: 2
                maxIdle: 2
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://pashionweb.c7nidmmcu7kv.us-east-1.rds.amazonaws.com:3306/pashionweb
            username: pashionweb
            password: ETWxa634WwxGaW6v
    production:
        elasticSearch:
            client:
                mode: local
                transport.sniff: true
            bulkIndexOnStartup: true
        dataSource:
            dbCreate: update
            url: jdbc:mysql://pashionweb.c7nidmmcu7kv.us-east-1.rds.amazonaws.com:3306/pashionweb
            username: pashionweb
            password: ETWxa634WwxGaW6v
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: pashion
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    json:
        legacy:
            builder: false
    servlet:
        version: 3.0
    resources:
        pattern: '/**'
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
        json:
            default:
                deep: false
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
